app = "magick"


[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 500
    soft_limit = 40

  [[services.ports]]
    handlers = []
    port = "80"

  [[services.ports]]
    handlers = ["tls", ]
    port = "443"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
